#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV

bspc config border_width         0
bspc config window_gap           3

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config bottom_padding       0.0
bspc config pointer_follows_focus true                                          
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

#AutoStart Applications
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &
